### PR TITLE
lausanne March achievements

### PR DESCRIPTION
**Pull request by gbataille**

### CODE REVIEW

**Comment by gbataille** [comment]
there is a conflict but I can't figure out why. I added on top of the latest upstream/master.... I'm not sure what I can do

**Comment by gbataille** [comment]
my bad. I'm not getting the latest commit but I'm not sure why. I'm having a look

**Comment by gbataille** [comment]
I'm stupid, all good

**Comment by aalmiray** [comment]
thanks! 😄

**Pull request merged**
