### PR TITLE
Add Softwerkskammer Ruhrgebiet Hackergarten event

### PR DESCRIPTION
**Pull request by georgberky**
We're hosting an event in September. Could you publish it on your homepage?

### CODE REVIEW

**Comment by aalmiray** [comment]
That's great news @georgberky! Does anyone in the organization team has previous experiences with Hackergarten?

**Comment by georgberky** [comment]
We haven't organized a Hackergarten yet, but we've organized several Coding Dojos, Coderetreats and user group meetups. Some people on our orga team have attended a Hackergarten, but we'd surely be happy to get some input from experienced organizers if you could spare the time.

**Comment by madmas** [comment]
Hi @georgberky,
as I'm living not too far away, I can join the event and support you in moderating it, etc if you want to. Also I can support with organization :)

**Comment by georgberky** [comment]
Hi @madmas , thanks for merging. I sent you an email about organizing the event.

**Pull request merged**
